name: "Elvish installer"
description: "Install the Elvish shell in your runner, allowing you to write your workflow scripts using the Elvish language."
author: "Diego Zamboni <diego@zzamboni.org>"
inputs:
  version:
    description: "Elvish version to install. Default: 'HEAD'."
    required: false
    default: "HEAD"
  binary_name:
    description:
      "The name to give to the installed Elvish binary. Default: 'elvish'. In
      Windows runners, '.exe' is automatically added to this name."
    required: false
    default: "elvish"
  binary_dir:
    description:
      "The path where to install the Elvish binary. Default: 'auto', which
      installs at /usr/local/bin on Linux/macOS and C:\\Program Files\\Elvish on
      Windows."
    required: false
    default: "auto"
  architecture:
    description:
      "Architecture for which to fetch the binary. Default: 'auto', which
      installs the correct version according to the runner architecture. You can
      manually specify any of the architectures for which Elvish is available
      (see https://dl.elv.sh/)."
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: Install Elvish
      shell: bash
      run: |
        # Determine the installation dir if the parameter value is "auto",
        # depending on the runner OS
        binary_dir="${{ inputs.binary_dir }}"
        if [[ "${binary_dir}" == "auto" ]]; then
          case "${{ runner.os }}" in
            Linux|macOS)
              binary_dir="/usr/local/bin"
              ;;
            Windows)
              binary_dir='C:\Program Files\Elvish'
              ;;
          esac
        fi

        # Now determine the architecture to download if not specified
        elvish_arch="${{ inputs.architecture }}"
        elvish_ext=""
        if [[ "${{ inputs.architecture }}" == "auto" ]]; then
          case "${{ runner.os }}" in
            Linux)
              elvish_arch="linux-amd64"
              ;;
            Windows)
              elvish_arch="windows-amd64"
              elvish_ext=".exe"
              ;;
            macOS)
              elvish_arch="darwin-amd64"
              ;;
          esac
        fi

        # Check if we need to use sudo to install
        SUDO="sudo"
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          SUDO=""
        fi

        # Finally, download and install in the correct place, add it to GITHUB_PATH
        elvish_dest="${binary_dir}/${{ inputs.binary_name }}${elvish_ext}"
        elvish_url="https://dl.elv.sh/${elvish_arch}/elvish-${{ inputs.version }}${elvish_ext}"
        echo "Downloading ${elvish_url} into ${elvish_dest}"
        $SUDO mkdir -p "${binary_dir}"
        $SUDO curl -s -o "${elvish_dest}" "${elvish_url}"
        $SUDO chmod a+rx "${elvish_dest}"
        echo "${binary_dir}" >> $GITHUB_PATH

branding:
  icon: chevron-right
  color: green
