on: push

jobs:
  one:
    runs-on: windows-2019
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Testing extend path on Windows
        shell: bash
        run: |
          mkdir "/c/Program Files/Elvish"
          wget -O "/c/Program Files/Elvish/elvish" "https://dl.elv.sh/windows-amd64/elvish-HEAD.exe"
          echo 'C:\Program Files\Elvish' >> $GITHUB_PATH
      - name: Check path
        shell: bash
        run: |
          echo PATH=$PATH
