name: Test Elvish installer
on: push

jobs:
  test-elvish-installer:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        version: [HEAD, v0.15.0]
    steps:
      - name: Testing Windows environment
        shell: bash
        run: |
          echo PATH=$PATH
          echo runner.tool_cache=${{ runner.tool_cache }}

      - name: Install Elvish ${{ matrix.version }} on ${{ matrix.os }}
        uses: zzamboni/elvish-installer@main
        with:
          version: ${{ matrix.version }}

      - name: Test Elvish ${{ matrix.version }} on ${{ matrix.os }}
        run: |
          use re
          echo "Output of elvish -buildinfo:"
          elvish -buildinfo
          echo "Checking that installed version matches ${{ matrix.version }}..."
          pattern = "^${{ matrix.version }}$"
          if (==s ${{ matrix.version }} HEAD) { pattern = "^v.*-dev.*" }
          installed-version = (elvish -buildinfo -json | from-json)[version]
          if (re:match $pattern $installed-version) {
            echo "OK!"
          } else {
            echo "::error::Version mismatch - expected ${{ matrix.version }}, got "$installed-version
            exit 1
          }
        shell:
          elvish {0}
